"""Added Avatar Column

Revision ID: 7120a23527f0
Revises: 797c24f62856
Create Date: 2016-07-01 13:49:46.543439

"""

# revision identifiers, used by Alembic.
revision = '7120a23527f0'
down_revision = '797c24f62856'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
